### ISSUE TITLE
"unrelated" conflict with magit

### ISSUE THREAD

**Issue by brandelune** [nex3/perspective-el#129]
In your "Some Musings on Emacs Window Layouts" you suggest:
```
(setq display-buffer-alist
      '((".*" (display-buffer-reuse-window display-buffer-same-window))))
```
For some reason, this very weirdly conflicts with magit when I have 2+ frames with different front facing buffers.

-> in one frame, I do magit-status, stage modifications, and the moment I hit c to commit, the frame is killed, I am moved to the other frame and magit tells me that there is nothing staged in the new frame, do I want to commit everything ?

I don't know how to reproduce that in emacs -Q because I don't know how to load magit from emacs -Q, so it's probably only my system, but I'd like to know if it is reproduced on your system. If it is, it should be reported as a magit bug I guess.

**Comment by brandelune** [comment]
Considering the replies on the issue I raised on magit, may I suggest that you add a note to your code to explain that it may break packages that depend on the default behavior ?
https://github.com/magit/magit/issues/4132

**Comment by gcv** [comment]
This is a breaking change in Magit since its last released version (2.90.1). I disagree with it, and will comment on the ticket you linked to. If Magit maintainers do not implement the fix I recommend, I will indeed update my suggested setting to explicitly exclude `\*magit` buffers.

BTW, to run an Emacs package (or multiple packages) in a sandbox environment, one easiest way is to clone the [melpa](https://github.com/melpa/melpa) repository, and run this:

```shell
EMACS_COMMAND=/path/to/emacs/binary make sandbox INSTALL=package   # e.g., magit
```

Documentation: https://github.com/melpa/melpa/blob/fbd6153/CONTRIBUTING.org#test-your-recipe

**Comment by brandelune** [comment]
Thank you very much for your followup and for the help.

**Comment by gcv** [comment]
All right! Magit deployed the fix I suggested: https://github.com/magit/magit/commit/035c24055c0e111187d554a0a214d6f0cbfb4bf1, it's in MELPA now. I think we're all good here. 😁
