### ISSUE TITLE
persp-created-hook triggering in GUI when emacsclient -t used

### ISSUE THREAD

**Issue by zenspider** [nex3/perspective-el#141]
I'm seeing something that I think is different from the server-before-persp kludge I found in master. I've tweaked stuff to ensure I'm loading persp before `server-start`, then when I use emacsclient in the terminal (so, another frame? I guess?), when I start AND stop it it seems to trigger my `persp-created-hook`:

```
% emacs &

HOOK: emacs-startup
DONE: rwd-load-modes                                     in 0.00 sec
PERSP-MODE
creating perspective in /Users/ryan/
DONE: (rwd-load "./modes/persp-mode" nil t)              in 0.03 sec
Starting SERVER
...

% emacsclient -t .

...
creating perspective in /Users/ryan/
When done with a buffer, type C-x #
creating perspective in /Users/ryan/
No server buffers remain to edit
```

When I'm bringing up a buffer using `emacsclient -t` I'd prefer to altogether avoid persp-mode, or have the option to treat it as part of the current perspective... or something...

or at least be able to detect that it is trying to spawn a perspective in a non-gui window and skip it, OR that it is the same name as an existing perspective and skip it. 

something. I'm open to suggestion.

**Comment by gcv** [comment]
I'm having a hard time reproducing this problem. First of all (on a Mac), the `emacsclient` binary in my 27.1 build seems to ignore `-t` and always opens a graphical frame. Not sure what's going on here. Second, when I explicitly start an Emacs instance using `-nw`, the behavior you describe doesn't occur. `persp-created-hook` runs just once.

As for bypassing Perspective altogether in some types of frames, that sounds useful. At first glance, a reasonable approach is to have `persp-init-frame` run a user-provided predicate function (`persp-init-in-frame?` which defaults to `(lambda () t)`?). The best way I know to determine if a frame was created using `emacsclient` is `(frame-parameter frame 'client)`, which should be set to the server process object in frames created that way, and `nil` otherwise.

**Comment by zenspider** [comment]
I dunno... closing. I'll reopen if I get more repro.
