### ISSUE TITLE
Show only current persp in modestring

### ISSUE THREAD

**Issue by titibandit** [nex3/perspective-el#150]
This is more of a suggestion than anything,
What about being able to only show the current persp in the mode/headerline instead of the entire list with the dividers and all?
I have it in my modeline, and since I have quite a few different perspectives, this list completely clutters my modeline. 
Having just the current selected persp in the modestring, I could still be able to quickly see the entire list by calling "persp-switch".
Cheers!

**Comment by gcv** [comment]
Good idea. I keep persp-show-modestring off in my own use, which is why I haven’t run into this problem. I’ll try to get to implementing this in a few days, but in the meanwhile, try putting the following in your configuration _after_ Perspective loads:

```elisp
(defun persp-update-modestring ()
  (when persp-show-modestring
    (set-frame-parameter nil 'persp--modestring (persp-current-name))))
```

This is completely untested. 😁 If it doesn’t work, you’ll have to reload Perspective, since it overrides an existing function.

**Comment by dams** [comment]
This is mor a suggestion and workaround than a direct answer but I think it can be useful information. 

To avoid this problem I use mini-modeling (https://github.com/kiennq/emacs-mini-modeline) which displays the modeline in the modeline buffer. Effectively it means that there is only one modeline, instead of one per window. The result is a much longer modeline, with enough space for displaying perspective names.

**Comment by titibandit** [comment]
@gcv 
Thanks, this works for now. It, for some reason is stuck to the rest of the modeline content. By that I mean it could use a space or something...but it works!
@dams That's a brilliant suggestion! I think I'll even use it in tandem with my suggestion, since the less clutter the better in my book.

**Comment by gcv** [comment]
@titibandit: You can fix the spacing by adjusting the format string in the definition below:

```
(defun persp-update-modestring ()
  (when persp-show-modestring
    (set-frame-parameter nil 'persp--modestring (format " %s" (persp-current-name)))))
```

**Comment by gcv** [comment]
I added a new customization setting, `persp-modestring-short`. Set it to `t` to enable this feature (don't forget to get rid of the hacked up `persp-update-modestring`).

**Comment by titibandit** [comment]
Great, this works!
I can then close the issue.
However, I would like to still have the perspective to be displayed using the persp-selected-face face, which I could do using:
```
(defun persp-update-modestring ()
  "Update the string to reflect the current perspectives.
Has no effect when `persp-show-modestring' is nil."
  (when persp-show-modestring
    (let ((open (list (nth 0 persp-modestring-dividers)))
          (close (list (nth 1 persp-modestring-dividers)))
          (sep (nth 2 persp-modestring-dividers)))
      (set-frame-parameter nil 'persp--modestring
           (append open
                   (if persp-modestring-short
                       (list (if (equal (persp-current-name) nil) nil (propertize (persp-current-name) 'face 'persp-selected-face)))
                     (persp-intersperse (mapcar 'persp-format-name
                                                (persp-names)) sep))
                   close)))))
```
And of course you can still "reverse" it by having a persp-selected-face that does nothing.
I don't know if that should be included, or if that only belongs to my personal config... you tell me!
Anyway, thanks for the commit :)

**Comment by gcv** [comment]
How about: (1) make a dedicated face for this purpose, like `persp-modestring-short-face`, and (2) make it a bit less loud than `persp-selected-face`, maybe just `(:weight bold)`.

You don't need to do `(if (equal something nil) ...)`, just `(if something ...)` suffices. :)

Feel free to open a PR.
