### ISSUE TITLE
2.0 change of persp-curr from var to fn returning custom type breaking change

### ISSUE THREAD

**Issue by chadhs** [nex3/perspective-el#69]
this change breaks the ability to grab the current perspective's name; 
example:

```emacs-lisp
(evil-leader/set-key
  "sv" (lambda () (interactive)         ; toggle (s)hell (v)isor
         (multi-term-dedicated-toggle)
         (multi-term-dedicated-select))
  "sn" (lambda () (interactive)         ; toggle (s)hell (n)ew
         ;; update buffer name setting dynamically for each perspective
         (setq-default multi-term-buffer-name (concat "term-" (elt persp-curr 1)))
         (multi-term)))
```

updating this to be a function call to `(persp-curr)` doesn't resolve the issue as any sequence functions won't work on the return value since type-of is a custom type perspective.

```
ELISP> (type-of (persp-curr))
perspective
```

**Comment by nex3** [comment]
`persp-curr` was never a sequence; it was always a perspective struct. It's possible that structs counted as sequences at one point and no longer do, possibly because the version of `cl-lib` you're using changed, but the proper way to get the name of a perspective in any case is with the `persp-name` function.
